### ISSUE TITLE
Output marshalled common data

### ISSUE THREAD

**Issue by ETatuzova** [NilFoundation/proof-producer#31]
To prevent running preprocessor twice, we need to write common data marshalling to file.
It will be an input for transpiler and recursive_gen apps instead of full assignment table.

**Comment by kazakova-e** [comment]
without this task we can't continue from small tests to production(highload) because recursive_gen - is single-threaded and its unable to run placeholder_preprocessor for highload production tests in a reasonable time

also, for Lido MVP purposes it will be suitable when preprocessed_public_data::common_data wil be outputed by proof-producer.
